### ISSUE TITLE
When "step-2" is clicked, nilavu spins for ever, and never moves to step-3 in new launcher.

### ISSUE THREAD

**Issue by rajesh-rajagopal** [megamsys/nilavu#943]
Its worked after stop / start the nilavu in terminal.

Vertice log show error

``` ruby
undefined method `map' for nil:NilClass
prepackaged_scrubber.rb:25:in `block in scrubbed'
prepackaged_scrubber.rb:24:in `map'
prepackaged_scrubber.rb:24:in `scrubbed'
marketplace_groups.rb:30:in `find_by_group'
launchable_scrubber.rb:9:in `prepackaged'
launchable_scrubber.rb:28:in `scrub'
launchables_controller.rb:23:in `prepare'
global_exceptions.rb:4:in `catch_exceptions'

      ,--.!,
   __/   -*-
    ,####.  '|`
    ######
    `####'                !We flunked!
```

Completed 200 OK in 5ms

**Comment by indykish** [comment]
Caused due the **Rails.cache** getting expired when looking for `prepackaged marketplace bifurs`"

**Comment by indykish** [comment]
Yes, confirmed this is a cache problem, the cache expires at 10 mins. Wonder why it doesn't pull data gain  ?

**honey_pot.rb**

``` ruby

  # groups with settings_name (vertice, bitnami, containership...)
  def self.cached_marketplace_bifurs(params)
    Rails.cache.fetch("honeypot_bifurs", expires_in: 10.minutes) do
      Api::Marketplaces.instance.list(params).marketplace_bifurs
    end
  end

```

http://guides.rubyonrails.org/caching_with_rails.html
https://signalvnoise.com/posts/3113-how-key-based-cache-expiration-works
http://api.rubyonrails.org/classes/ActiveSupport/Cache/Store.html

**Comment by indykish** [comment]
The fix is to add `race_condition_ttl: 10`.  It works now.

What is `race_condition_ttl: 10` => RTM http://guides.rubyonrails.org/caching_with_rails.html

``` ruby

# groups with settings_name (vertice, bitnami, containership...)
  def self.cached_marketplace_bifurs(params)
    Rails.cache.fetch("honeypot_bifurs", race_condition_ttl: 10, expires_in: 10.minutes) do
      Api::Marketplaces.instance.list(params).marketplace_bifurs
    end
  end

```

**Comment by indykish** [comment]
Well, i removed "expires".

RTM http://guides.rubyonrails.org/caching_with_rails.html

``` ruby

# groups with settings_name (vertice, bitnami, containership...)
  def self.cached_marketplace_bifurs(params)
    Rails.cache.fetch("honeypot_bifurs", race_condition_ttl: 10) do
      Api::Marketplaces.instance.list(params).marketplace_bifurs
    end
  end
```
